# Generated by Django 5.0 on 2024-01-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0006_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_review',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
