# Generated by Django 5.0 on 2024-01-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0007_watchlist_avg_review_watchlist_number_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='avg_review',
            new_name='avg_rating',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='number_reviews',
            new_name='number_rating',
        ),
    ]
