# Generated by Django 5.0 on 2024-02-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0008_rename_avg_review_watchlist_avg_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='review_user',
        ),
    ]
